site_name: Final Project Documentation
site_url: https://canting9.github.io/Spatial-Audio/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy


nav:
  - Introduction and Concept: intro-concept.md
  - Technical Details: tech-details.md
  - Documentation of the Show: documentation.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - footnotes
  - attr_list
